### ISSUE TITLE
Cantonese support

### ISSUE THREAD

**Issue by ddcc** [ThoreBor/CC-CEDICT-for-Anki#11]
Would it be possible to add cantonese support using the [CC-Canto](https://cantonese.org/download.html), including jyutping? I don't know if it'd be better to have both in the same extension, or separate ones.

**Comment by ThoreBor** [comment]
The link doesn't work for me. Do you mean this: https://cantonese.org/download.html ?

**Comment by ddcc** [comment]
Oops, yeah, that's what I meant.

**Comment by ThoreBor** [comment]
Alright. It looks like I wouldn't have to change much to make it work. I have to update the add-on anyway (probably in early October) so I'll see if I include it, or make a separate new add-on for it.

**Comment by ThoreBor** [comment]
When making the database for the cc-cedict dictionary I converted the pinyin + numbers to pinyin with tone marks.
Ex: 一九九七年 一九九七年 [yi1 jiu3 jiu3 qi1 nian2] /Year 1997/ to 一九九七年 一九九七年 [yījiǔjiǔqīnián] /Year 1997/
Is there a similar conversion for {jat1 gau2 gau2 cat1 nin4} or is it usually just with numbers?

**Comment by ddcc** [comment]
Nope, just with numbers. Thanks!

**Comment by ThoreBor** [comment]
Hi, sorry for the delay. I decided to make a new add-on for this, instead of including it in this one. You can check it out [here](https://github.com/ThoreBor/CC-Canto-for-Anki) and download a pre-release [here](https://github.com/ThoreBor/CC-Canto-for-Anki/releases/tag/v0.1). You just have to download the `.ankiaddon` file and open it to install the add-on. 
Keep in mind that I don't speak nor learn Cantonese, so please let me know if I have to change something or just what you think in general.

**Comment by ddcc** [comment]
No problem, thanks for creating the new add-on! I'll try it and get back to you.

**Comment by ddcc** [comment]
I've tried it and reported a couple of bugs in https://github.com/ThoreBor/CC-Canto-for-Anki/issues/1.
