### ISSUE TITLE
Feature: auto detect input

### ISSUE THREAD

**Issue by HappyRay** [ThoreBor/CC-CEDICT-for-Anki#17]
I think it may be possible to avoid asking users to select what the input type is ( simplified, traditional, English).

For example, can the code search for results assuming one type at a time until it finds matches?

**Comment by ThoreBor** [comment]
I also thought about this. Determining whether the input is Chinese or English could be done by modifying [this function](https://github.com/ThoreBor/ChineseWordsFinder/blob/1debd336ebb378432516a01aa47d938ecbd4791e/getdata.py#L5). [Mafan](https://github.com/hermanschaaf/mafan) could test whether the input is simplified or traditional. Since this module is not included in Anki it would have to be bundled with the add-on (see [Anki add-on docs](https://addon-docs.ankiweb.net/#/more?id=standard-modules))

> can the code search for results assuming one type at a time until it finds matches

Maybe something like this:
```
input_types = ["hanzi_simp", "hanzi_trad", "eng"]
for i in input_types:
    c.execute("SELECT * FROM dictionary WHERE (%s) = (?)" % (i), (word,))
    result = c.fetchall()
    if not result:
        continue
    else:
        break
```
I could see this produce some inaccurate results, though. For example someone using traditional characters might search for 里. The correct result would be:
1. Li (surname)
2. li, ancient measure of length, approx. 500 m, neighborhood, ancient administrative unit of 25 families, (Tw) borough, administrative unit between the township 鎮|镇(zhèn) and neighborhood 鄰|邻(lín) levels

But it would also return:

1. variant of 裡|里(lǐ)
2. lining, interior, inside, internal, also written 裏|里(lǐ)

That's because 里 is also the simplified version of 裏 and 裡.

**Comment by HappyRay** [comment]
Since I don't use traditional Chinese, I am not familiar with the nuances. 

Would it work if you treat the language selection as a hint i.e. search based on the selected language first and fall back to the automatic detection algorithm you described above? This way, users can still handle the rare cases and common cases are simplified.

**Comment by ThoreBor** [comment]
I'm not sure if I understand what you mean. I could add an "auto detect input" option to the dropdown menu, which could be the default option and keep the other options, so users can specify the input if needed. Something like that?

**Comment by HappyRay** [comment]
Let me try to clarify with examples.

Users select English as the input type and type in traditional Chinese. The program will search assuming the input is English first. In this case, there shouldn't be any match. It then tres the other input languages in turn until a match is found. 

If the result is not what users expect, users can change the input type to the desired one and try again. 

Does it make sense?

**Comment by ThoreBor** [comment]
Okay, got it. So just in case the user chose the wrong input type. That could work.

**Comment by HappyRay** [comment]
It's more than that. I suspect that with such a change, users don't need to worry about choosing the right type in most cases.

**Comment by HappyRay** [comment]
When do you plan to make a new release?

**Comment by ThoreBor** [comment]
I still have to implement the auto-detect feature. And I'm not sure if I should add CC-Canto to this add-on, or just make a new one (#11). What do you think?
I'm a little busy at the moment, but I think either way I could release the new version within the month.

**Comment by HappyRay** [comment]
Cool.   
I personally prefer frequent incremental releases. It's useful to shorten the feedback loops. 

Sorry, I am not familiar with the Canto support enough to have an opinion. 

I am looking forward to testing your new release. Thanks.

**Comment by ThoreBor** [comment]
I decided that I'm going to use [mafan](https://github.com/hermanschaaf/mafan) after all. That way the detection of the input is, as far as I can tell, very accurate. Selecting an input type is therefore no longer necessary. Like I said because it's not a standard module I had to bundle it (and [jieba](https://github.com/fxsjy/), a dependency) up with this add-on. For now, I uploaded both modules to GitHub, but I don't know how much sense that makes, because it's a lot of code and I only had to change a few lines in  [text.py](https://github.com/ThoreBor/CC-CEDICT-for-Anki/blob/master/third_party_packages/mafan/text.py)
Please let me know what you think and if you find any bugs.

**Comment by ThoreBor** [comment]
Nevermind, I don't think that was such a good idea. I'll revert the changes in a moment.

**Comment by ThoreBor** [comment]
Okay, I think it works now. I'm now using [hanzidentifier](https://github.com/tsroten/hanzidentifier) instead of mafan. I like it better this way and it fixed some problems that I found after the initial commit.

**Comment by HappyRay** [comment]
Cool. I am rebuilding my dev machine. So it may take a while before I can test it.

**Comment by ThoreBor** [comment]
No problem!
