### ISSUE TITLE
Feature: Colour pinyin according to tone

### ISSUE THREAD

**Issue by sykul** [ThoreBor/CC-CEDICT-for-Anki#21]
I really like the way this HSK deck colours its pinyin according to tone; https://ankiweb.net/shared/info/1855818143 It makes absorbing the tones much easier.
It uses an html <span> element with class= tone1, tone2, tone3 or tone4 and uses CSS in the card template accordingly.
Perhaps card templates can't be controlled by this addon, however I think it shouldn't be too complicated to add html elements to the pinyin and you could advise users in the instructions to add CSS styling if they want to.

**Comment by ThoreBor** [comment]
I'm not sure if I can do this, because I think the pinyin is not separated by spaces in the dictionary. I'll see what I can do. 
I'm not sure when I have time for these issues. It might take a while. But I just realized, that I updated a bunch of stuff months ago and didn't release it on Ankiweb yet, so thanks for reminding me. I'll try to release an update soon.

**Comment by sykul** [comment]
The pinyin is separated by spaces in the original txt file from CC-CEDICT, so perhaps simply adding a space somewhere in tools/database.py would solve that. 
As for the html, perhaps that could be inserted with a formatted string somewhere in the add_note function? Do you know whether html can be inserted that way?

P.S. Looking forward to the update.

**Comment by ThoreBor** [comment]
I released a pre-release here on Github with your features. If you want, you can test it by downloading the .ankiaddon file from [here](https://github.com/ThoreBor/CC-CEDICT-for-Anki/releases/tag/v1.3-beta). Please let me know if you find any bugs :)
