### ISSUE TITLE
Feature: batch input mode

### ISSUE THREAD

**Issue by HappyRay** [ThoreBor/CC-CEDICT-for-Anki#3]
I found this tool a great time saver for me. Thanks for sharing it!

I typically would add a few phrases at a time. It would be great if this tool can have a batch input mode. This will further reduce the number of manual work.

Here is one possible design I can think of:

If the input contains multiple phrases separated by space, the batch input mode is turned on automatically and the exact match mode is used automatically to search each phrase.
If a match is found, it will be displayed in the list below the search box. 
The ones that can't find a match will be displayed below the matched list.
When the add button is clicked, the matched ones will be added. 

What do you think?

**Comment by ThoreBor** [comment]
I like the idea. So I'm assuming your search query consists of Chinese words, right? It's probably better to separate the words with a comma, or something else **not** a space so it also works for English words/phrases. 
I'm planning to update the add-on soon (rewrite some parts and especially reorganize the code), but I'm currently quite busy. I'll probably have time for it in October.

**Comment by HappyRay** [comment]
Thanks.
Yes, my use case is for Chinese inputs.
I agree a comma is a better choice than spaces if other languages are supported.

**Comment by HappyRay** [comment]
I found an alternative way to add new notes. It doesn't require creating a file first. 
See my test for details
https://github.com/HappyRay/anki-addon-test/blob/v0.1/__init__.py
It took me some time to figure out how to configure the right node type to use with this tool. I think it may be easier to automatically create a node type for this tool.

**Comment by HappyRay** [comment]
Where did you download the dictionary database file? I can only find the text version from the https://www.mdbg.net/chinese/dictionary?page=cedict download site.

**Comment by HappyRay** [comment]
Since I don't know other ways to communicate with you, I am using this comment thread instead. Please let me know if you prefer an alternative way to get in touch. e.g. Linkedin messages.

**Comment by ThoreBor** [comment]
Looks good!
I wrote a script that makes a database out of the text file.
I just push a few changes. I reorganized everything a bit. Let me know if you find any errors. This way it's a little easier to implement the changes. The Ui looks a bit different at the moment, but I'll take care of it when I have time.

This thread is fine, I don't have Linkedin.

**Comment by HappyRay** [comment]
Got it. It's cool. 
It would be great if you can share that tool too. I suspect others may find that script useful.

**Comment by ThoreBor** [comment]
Just uploaded it into the tools folder.

**Comment by HappyRay** [comment]
Thanks!

**Comment by HappyRay** [comment]
FYI I implemented a version in my fork
https://github.com/HappyRay/CC-CEDICT-for-Anki/tree/batch-input
It currently only supports Simplified Chinese.
I've used it for some time and it worked fine for me.

**Comment by ThoreBor** [comment]
Ah okay, thanks for letting me know. I just implemented batch search yesterday. It works for traditional, simplified, and English. I'm using / instead of ，because it's the same in English and Chinese. I didn't write the batch input part yet though. I think your add_note and add_multiple_notes functions are better than add_cards.  Your main.py and my main.py differ in a way that they can't be merged at the moment, so I'm not sure what to do now. I didn't make a lot of changes so if you want you can just make a pull request and I overwrite the current version and adjust some stuff afterwards. Or do you have a better idea?

**Comment by HappyRay** [comment]
Ok, let me take a look at your changes.

**Comment by HappyRay** [comment]
I added my existing change on top of your changes. See #12 

This way both of our changes are preserved. I can help consolidate the code and simplify it in the future if you would like. 

To keep the main repo's git history cleaner ( without the merge commits ), you may consider choosing the 
Squash and merge your pull request commits option or 
Rebase and merge your pull request commits option as you see fit.
see
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges

**Comment by ThoreBor** [comment]
Thanks again for your pull request. I just implemented batch import/search for traditional characters and English. I also simplified the code a bit. 
I just have one question: In  your `search_word` function (which is now `exact_match`) you call `c.fetchone()` instead of `c.fetchall()`. This probably works for most cases, but could cause some trouble with characters that have more than one meaning/pronunciation.  For example, there are three entries in the dictionary for 還/还. Was this on purpose, maybe because you don't want to import more notes than words you searched for? I think it's probably better to add all results, so I might change that unless it's for a good reason.

I also noticed that I can't change the notetype for the imported notes. They get imported but the notetype set in the config is ignored and I couldn't figure out why that's the case yet.

And sure, if you have any ideas on how to improve, simplify, and/or consolidate the code let me know.

**Comment by HappyRay** [comment]
I can see the result code is cleaner after your simplification. Thanks.

Re: fetchone vs fetchall. I didn't realize that there can be multiple entries in the dictionary for one word. I guess it is designed to handle cases when a word has multiple pronunciations. It seemed to me your earlier implementation would fetch one entry in the exact match mode in such a case also. I tried to mimic that behavior with less code. It's possible that my understanding of your existing code is wrong though. Please feel free to change this behavior. It's reasonable to add all such entries in such a case. Users can delete the unwanted entries later. Thanks

**Comment by HappyRay** [comment]
Yes, I also noticed the same issue with a wrong note type selected. It used to work for me. I will also look into it.

**Comment by ThoreBor** [comment]
Alright, I changed it back to fetchall.
Instead of using 'Simplified' etc. as default field names, users can now select a notetype and then choose the field they want to use for simplified, pinyin etc. I think it's easier and more flexible this way.
